//npm packages
import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link, Redirect } from 'react-router-dom';

//local imports
import './SignIn.css';
import NavBar from '../../../components/nav_bar/NavBar';
import CustomModal from '../../../components/custom_modal/CustomModal';
import { signInAction, clearMessagesAction } from '../../../store/actions/authActions';


/**
 * #LOGIN PAGE
 */
const SignIn = () => {
    
    
    /**
     * #FORM VALUES
     */
    const [ email, setEmail ] = useState('');
    const [ password, setPassword ] = useState('');
        
    /**
     * #SUBMITTING FORM
     * #DISPATCH AN ACTION AND THEN STORE THE RESPONSE ON REDUX STATE
     * E.G SUCESS OR FAILURE MESSAGES OR API-KEY
     */
    const dispatch = useDispatch();
    const handleSubmit = () => dispatch(signInAction({ email, password }));
    
    
    /**
     * #DATA STORED ON REDUCER FOR ASYNC CALLS
     */
    const message = useSelector((state) => state.auth.message);
    const isLoading = useSelector((state) => state.auth.isLoading)

    /**
     * #WHEN SENDING FORM RENDER THE LOADING FORM
     */
    const isButtonDisabled = loading => loading ? 'sign-in-button-disabled' : 'sign-in-button';

    /**
     * #CLEAR ERROR OR SUCESS MESSAGES AFTER 4s
     */
    setTimeout(() => {
        message.length > 0 && dispatch(clearMessagesAction());
    }, 4000);

    /**
     * #ACCESS API-KEY GENERATED BY THE NODE SERVER FROM LOCAL STORAGE AND USE IT TO LOG IN USERS
     */
    const apiKey = window.sessionStorage.getItem("api-key");

    if (apiKey) {
        return <Redirect to="/"/>;
    }

    return (
        <>
        <NavBar />
        <div className='sign-in'>
            <img className='sign-in-bg-image' src='/assets/images/bg/cartBg.jpg' alt='background img' />
                <div className='sign-in-wrapper'>
                    <div className='sign-in-form'>
                        <h3 className="sign-in-header">
                            SIGN IN
                        </h3>
                        <div className='sign-in-label-input-box'>
                            <label className='sign-in-label'>E-MAIL</label>
                            <br/>
                            <input
                                className='sign-in-input'
                                type="email" 
                                name="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                            />
                        </div>
                        <div className='sign-in-label-input-box'>
                            <label className='sign-in-label'>PASSWORD</label>
                            <br />
                            <input
                                className='sign-in-input'
                                type="password"
                                name="password"
                                onChange={(e) => setPassword(e.target.value)}
                            />
                        </div>
                        <button
                            className={isButtonDisabled(isLoading)}
                            type="submit"
                            onClick={() => handleSubmit()}
                            disabled={isLoading}
                        > SIGN IN </button>

                        <Link className='link' to='/auth/signup'>
                            <p className='sign-in-signup-link'>Create new account</p>
                        </Link>
                </div>
            </div>
            {
                message ? 
                    <CustomModal>
                        <p className='failure-message'>{ message }</p>
                    </CustomModal>
                    : ''
            }
        </div>
        </>
    )
}

export default SignIn;